version: '3.8'
services:
  db:
    image: postgres:15.4
    container_name: go-api-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # 初期化データを変更する場合はpostgres-dataディレクトリを削除する必要がある
      # - ./data-init:/docker-entrypoint-initdb.d